### ISSUE TITLE
"Failed to activate the copy-config-info package"

### ISSUE THREAD

**Issue by knobhead** [postcasio/copy-config-info#2]
Hi there,

I tried to activate your helpful plug-in via the command palette but got this error.

**Atom Version**: 1.0.0
**System**: Win7
**Thrown From**: [copy-config-info](https://github.com/postcasio/copy-config-info) package, v0.4.0

### Stack Trace

Failed to activate the copy-config-info package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (C:\Users\philipp.krieger\.atom\packages\copy-config-info\lib\copy-config-info.coffee:3:21)
  at Package.module.exports.Package.activateNow (D:\<username>\Tools\Atom\resources\app.asar\src\package.js:240:19)
  at D:\<username>\Tools\Atom\resources\app.asar\src\package.js:772:25
  at Emitter.module.exports.Emitter.emit (D:\<username>\Tools\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\<username>\Tools\Atom\resources\app.asar\src\command-registry.js:222:20)
  at D:\<username>\Tools\Atom\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (D:\<username>\Tools\Atom\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (D:\<username>\Tools\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (D:\<username>\Tools\Atom\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\<username>\Tools\Atom\resources\app.asar\src\command-registry.js:241:29)
  at D:\<username>\Tools\Atom\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\<username>\Tools\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\<username>\Tools\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at WindowEventHandler.module.exports.WindowEventHandler.onKeydown (D:\<username>\Tools\Atom\resources\app.asar\src\window-event-handler.js:180:20)
  at AltGrManager.module.exports.AltGrManager.onKeydown (C:\Users\philipp.krieger\.atom\packages\altgr\lib\altgr-manager.coffee:35:29)
  at HTMLDocument.module.exports.Altgr.onKeydown (C:\Users\philipp.krieger\.atom\packages\altgr\lib\altgr.coffee:28:16)

```

### Commands

```
     -0:42.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai-syntax-for-one-dark.theme-one-dark-ui)
     -0:13.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.7.0 copy-config-info:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-syntax-for-one-dark"
    ],
    "disabledPackages": [
      "emmet",
      "markdown-preview-opener"
    ]
  }
}
```

### Installed Packages

```coffee
# User
altgr, v0.1.0
autocomplete-php, v0.3.6
color-picker, v2.0.7
compare-files, v0.6.1
copy-config-info, v0.4.0
docblockr, v0.7.2
emmet-simplified, v2.4.2
file-icons, v1.5.8
indentation-indicator, v0.6.0
language-batch, v0.3.3
linter, v1.1.0
linter-php, v0.0.15
markdown-scroll-sync, v0.4.0
minimap-bookmarks, v0.1.0
minimap-linter, v1.0.0
minimap-selection, v4.3.0
monokai-syntax-for-one-dark, v0.2.2
open-recent, v2.2.4
useful-context-menu, v0.2.1

# Dev
No dev packages
```

**Comment by rugk** [comment]
Same issue here: https://github.com/atom/atom-dark-syntax/issues/19

**Comment by aioue** [comment]
+1

**Comment by rugk** [comment]
@aioue
The list of packages is already included in the automatically created bug report. I don't see any reason to list them again. (Also don't know what kind of workaround this should be :confused:)
